export const SHOP_TAGS = [
  "bubble_tea",
  "matcha",
  "bakery",
  "bingsu",
  "meals",
  "asian_grocery",
  "fashion",
  "photo_booths",
  "artist_goods",
  "lifestyle",
  "cosmetics",
  "anime_goods",
  "manga",
  "gundam",
  "blind_boxes",
  "gachas",
  "ichiban_kuji",
  "cartoon",
  "chiikawa",
  "disney",
  "jellycat",
  "miffy",
  "mofusand",
  "monchhichi",
  "sanrio",
  "smiski",
  "sonny_angel",
  "studio_ghibli",
  "sylvanian_families",
] as const;

export type ShopTag = (typeof SHOP_TAGS)[number];

export const FOOD_DRINK_TAGS = [
  "bubble_tea",
  "matcha",
  "bakery",
  "bingsu",
  "meals",
  "asian_grocery",
] as const satisfies readonly ShopTag[];

export type FoodDrinkTag = (typeof FOOD_DRINK_TAGS)[number];

export const RETAIL_SHOP_TAGS = [
  "fashion",
  "photo_booths",
  "artist_goods",
  "lifestyle",
  "cosmetics",
  "anime_goods",
  "manga",
  "gundam",
  "blind_boxes",
  "gachas",
  "ichiban_kuji",
  "cartoon",
  "chiikawa",
  "disney",
  "jellycat",
  "miffy",
  "mofusand",
  "monchhichi",
  "sanrio",
  "smiski",
  "sonny_angel",
  "studio_ghibli",
  "sylvanian_families",
] as const satisfies readonly ShopTag[];

export type RetailShopTag = (typeof RETAIL_SHOP_TAGS)[number];

export const SHOP_TAG_LABELS: Record<ShopTag, string> = {
  bubble_tea: "Bubble & fruit tea",
  matcha: "Matcha",
  bakery: "Cakes & pastries",
  bingsu: "Bingsu",
  meals: "Meals",
  asian_grocery: "Asian grocery",
  fashion: "Fashion",
  photo_booths: "Photo Booths",
  artist_goods: "Artist Goods",
  lifestyle: "Lifestyle",
  cosmetics: "Cosmetics",
  anime_goods: "Anime Goods",
  manga: "Manga",
  gundam: "Gundam",
  blind_boxes: "Blind Boxes",
  gachas: "Gachas",
  ichiban_kuji: "Ichiban Kuji",
  cartoon: "Cartoon",
  chiikawa: "Chiikawa",
  disney: "Disney",
  jellycat: "Jellycat",
  miffy: "Miffy",
  mofusand: "Mofusand",
  monchhichi: "Monchhichi",
  sanrio: "Sanrio/San-X",
  studio_ghibli: "Studio Ghibli",
  smiski: "Smiski",
  sonny_angel: "Sonny Angel",
  sylvanian_families: "Sylvanian Families",
};

export const TAG_COLORS: Record<ShopTag, string> = {
  bubble_tea: "#F3E6DC",
  matcha: "#F3E6DC",
  bakery: "#F3E6DC",
  bingsu: "#F3E6DC",
  meals: "#F3E6DC",
  asian_grocery: "#F3E6DC",
  fashion: "#E8D0DC",
  photo_booths: "#D5DDD4",
  artist_goods: "#E2D4F0",
  anime_goods: "#F0D0E0",
  manga: "#F0D0E0",
  gundam: "#D0DCEC",
  blind_boxes: "#D4DBE4",
  gachas: "#D4DBE4",
  ichiban_kuji: "#D4DBE4",
  monchhichi: "#EAD8DE",
  sanrio: "#EAD8DE",
  smiski: "#EAD8DE",
  sonny_angel: "#EAD8DE",
  sylvanian_families: "#EAD8DE",
  mofusand: "#EAD8DE",
  miffy: "#EAD8DE",
  disney: "#EAD8DE",
  chiikawa: "#EAD8DE",
  cartoon: "#EAD8DE",
  jellycat: "#EAD8DE",
  studio_ghibli: "#EAD8DE",
  lifestyle: "#D5DDD4",
  cosmetics: "#D5DDD4",
};

export const MELBOURNE_CENTER = { lat: -37.8136, lng: 144.9631 } as const;

export const STATUS = ["pending", "approved"] as const;
export type Status = (typeof STATUS)[number];

export const MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
] as const;
