import type { Event, Shop } from "./types";

export const SEED_EVENTS: Event[] = [
  {
    id: "e1",
    title: "Kawaii Market at Queen Victoria",
    slug: "kawaii-market-queen-victoria",
    description:
      "A weekend market stall row of cute illustrators, blind boxes, and plush traders.",
    start_at: new Date(new Date().getFullYear(), 5, 14, 10, 0).toISOString(),
    end_at: new Date(new Date().getFullYear(), 5, 15, 16, 0).toISOString(),
    venue_name: "Queen Victoria Market",
    address: "Queen St, Melbourne VIC 3000",
    lat: -37.8076,
    lng: 144.9568,
    image_url: null,
    external_url: null,
    status: "approved",
    admin_note: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "e2",
    title: "Pop-up Art Gallery: Pastel Dreams",
    slug: "pastel-dreams-popup",
    description:
      "Local artists showcase kawaii illustrations, stickers, and zines. Free entry, donations welcome.",
    start_at: new Date(new Date().getFullYear(), 6, 5, 11, 0).toISOString(),
    end_at: null,
    venue_name: "Flinders Lane Studio",
    address: "45 Flinders Ln, Melbourne VIC 3000",
    lat: -37.815,
    lng: 144.971,
    image_url: null,
    external_url: null,
    status: "approved",
    admin_note: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "e3",
    title: "Sonny Angel Swap Meet",
    slug: "sonny-angel-swap-meet",
    description:
      "Bring your doubles and trade with fellow collectors. Beginner-friendly vibe.",
    start_at: new Date(new Date().getFullYear(), 7, 20, 13, 0).toISOString(),
    end_at: new Date(new Date().getFullYear(), 7, 20, 18, 0).toISOString(),
    venue_name: "Community Hall Carlton",
    address: "220 Rathdowne St, Carlton VIC 3053",
    lat: -37.8,
    lng: 144.966,
    image_url: null,
    external_url: null,
    status: "approved",
    admin_note: null,
    created_at: new Date().toISOString(),
  },
];

export const SEED_SHOPS: Shop[] = [
  {
    id: "s1",
    name: "Monchhichi & Co.",
    slug: "monchhichi-and-co",
    description: "Vintage Monchhichi plush, keychains, and gift sets in the CBD.",
    address: "Shop 12, Melbourne Central, Melbourne VIC 3000",
    lat: -37.8105,
    lng: 144.963,
    website: null,
    hours: "Mon–Sat 10am–6pm",
    image_url: null,
    status: "approved",
    admin_note: null,
    created_at: new Date().toISOString(),
    shop_tags: ["monchhichi"],
  },
  {
    id: "s2",
    name: "Pastel Parfait House",
    slug: "pastel-parfait-house",
    description: "Kawaii desserts, parfaits, and character latte art.",
    address: "88 Bourke St, Melbourne VIC 3000",
    lat: -37.813,
    lng: 144.968,
    website: null,
    hours: "Daily 11am–7pm",
    image_url: null,
    status: "approved",
    admin_note: null,
    created_at: new Date().toISOString(),
    shop_tags: ["desserts", "brunch"],
  },
  {
    id: "s3",
    name: "Smiski Corner",
    slug: "smiski-corner",
    description: "Smiskis, blind boxes, and cozy brunch plates on weekends.",
    address: "210 Bridge Rd, Richmond VIC 3121",
    lat: -37.818,
    lng: 145.004,
    website: null,
    hours: "Wed–Sun 11am–5pm",
    image_url: null,
    status: "approved",
    admin_note: null,
    created_at: new Date().toISOString(),
    shop_tags: ["smiski", "brunch", "desserts"],
  },
];
